### ISSUE TITLE
Mango stuck in infinite loop when Unknown BSON type

### ISSUE THREAD

**Issue by LLFourn** [oliwer/mango#1]
I don't really understand how I got this:

```
Mojo::Reactor::EV: Read failed: Unknown BSON type at /home/lfournier/perl5/perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/Mango/BSON.pm line 228.
	Mango::BSON::_decode_value('\x{6}', 'SCALAR(0x4cc7070)') called at /home/lfournier/perl5/perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/Mango/BSON.pm line 156
	Mango::BSON::_decode_doc('SCALAR(0x4cc7070)') called at /home/lfournier/perl5/perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/Mango/BSON.pm line 192
	Mango::BSON::_decode_value('\x{4}', 'SCALAR(0x4cc7070)') called at /home/lfournier/perl5/perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/Mango/BSON.pm line 156
	Mango::BSON::_decode_doc('SCALAR(0x4cc7070)') called at /home/lfournier/perl5/perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/Mango/Protocol.pm line 103
.....
```

Mango is then completely stuck in a while loop. If I figure out how this is happening I will let you know but just thought that you might want to fix the infinite loop on exception.

**Comment by oliwer** [comment]
Thank you for the report! I would be very interested in a reproducible test
case. I see here that you got a bson value of type 0x06 (Undefined), which
MongoDB is not supposed to produce anymore... I guess one possible way to
fix this would be to treat Undefined bson values same as Null values
(0x0a). But we cannot be sure of anything without a way reproduce this.



2015-01-05 6:42 GMT+01:00 LLFourn <notifications@github.com>:

**Comment by LLFourn** [comment]
Hi oliwer,

It took me a while to get around to this. I am very proud to say that I think I have figured it out. It's a bug in MongoDB to do with calling distinct on a field that is composed of arrays and has an index.
Run this:
```
use Mango;
my $m = Mango->new;
my $c = $m->db('foo')->collection('bar');
$c->insert({baz => []});
$c->ensure_index({baz => 1});
$c->find->distinct('baz');
```
And you get the unknown BSON type in mongodb 2.6.7. The bug shows up on the shell as well.

```
> db.bar.distinct('baz')
[ null ]
```
Where as it should just be an empty array. you don't get the null without the index.

And for some reason if you do this within Mojolicious:

```
use Mango;
use Mojolicious::Lite;
my $m = Mango->new;
my $c = $m->db('foo')->collection('bar');
$c->insert({baz => []});
$c->ensure_index({baz => 1});
$c->find->distinct('baz');
```
and run it with the morbo a server you will not be able to ctrl-c stop the process. I'm not sure why.

I guess I will have to file a bug report with Mongodb.
