### ISSUE TITLE
First pass authentication problem

### ISSUE THREAD

**Issue by sylvaint** [oliwer/mango#10]
mongodb 3 with Mango 1.22 Authentication SCRAM-SHA-1
No issue accessing db and data with mongo shell.

Mojolicious Lite app, first query after app started gives an access error "not authorized for query on dbName.collectionName".  Queries after the initial one work fine.

    use Mojolicous::Lite;
    use Mango;

    my $muri = 'mongodb://user:pass@localhost/mydb'; 
    my $mango = Mango->new($muri);

    get '/' => {
        my $c = shift;
        my $pos = $mango->db->collection('myCollection')->find->all;
        $c->render('json' => $pos);
    };
    app->start;

**Comment by alexbyk** [comment]
There is a similar (or maybe the same) problem when using mixed non-blocking and blocking requests and authentication is on. The very first query fails, but others run as expected
The bug lives in Mango/Auth/SCRAM.pm, but from the first look it it's simpler to rewrite both Mango.pm and Mango/Auth/SCRAM.pm modules from the scratch than fix this bug.

**Comment by sylvaint** [comment]
Same issue when upgrading an instance of mongodb 2.6 to 3 and keeping MONGODB-CR authentication on the existing data.  Very first query fails, but others run as expected.

**Comment by oliwer** [comment]
I may have found a quick and dirty fix for this. But i need little more testing first.

I agree with you alexbyk. Mango.pm is a bit obscure, and it will need to be rewritten to support replica sets anyway.

**Comment by oliwer** [comment]
@alexbyk What do you think about this solution?

https://github.com/oliwer/mango/compare/master...oliwer:bug10?expand=1

It does not seem to have any side-effect but it's hard to be sure.

**Comment by alexbyk** [comment]
@oliwer I'll check this today

**Comment by alexbyk** [comment]
@oliwer I checked this. It's hard to  track how and why this works, but it does. I updated Mango with your commit in my app in production, and all tests passed, all works as expected. So :+1:

**Comment by sylvaint** [comment]
@oliwer Same here.  Updated with your commit and tested multiple apps, blocking and non blocking with no issues.  Merci beaucoup pour le support.

**Comment by oliwer** [comment]
Great! I will make a release very soon.

@alexbyk From what I gathered, the _authenticate sub was stuck at the first step of the Mojo::Delay. By using `one_tick`, I force the program to finish the remaining steps before moving to something else. At least I think that's what it does...
