### ISSUE TITLE
Mango::Collection::insert modifies the parameters

### ISSUE THREAD

**Issue by JianleiZhang** [oliwer/mango#11]
From package Mango::Collection：
sub insert {
  ...
  # Make sure all documents have ids
  my @ids = map { $_->{_id} //= bson_oid } @$docs;
  ...
}

The variable transmission has been modified When I re-use this variable

**Comment by oliwer** [comment]
You're right. I wonder why it was written like that. I guess it can be seen as a feature?

Anyway, I will write a patch for this soon.

**Comment by oliwer** [comment]
Sorry for the delay, and thanks for the report!
