### ISSUE TITLE
Lack of documentation how to use Mango in helpers (issues related to weakened reference)

### ISSUE THREAD

**Issue by pavelsr** [oliwer/mango#17]
I think we should highlight in docs that db holds only a **weakened** reference to the mango instance (now it's only mentioned here: [1](https://metacpan.org/pod/Mango::Database#mango) and [2](https://metacpan.org/pod/Mango#db)), explain why is it and add examples how to use Mango at set default db in helpers.

E.g. following code will give an error ```Can't call method "query" on an undefined value at .../Mango/Cursor/Query.pm```: 

```perl
has dbh => sub {
  my $self = shift;
  my $mango = Mango->new('mongodb://localhost:27017');
  return $mango->db('mongopa');
};
...
 $self->app->dbh->collection('users')->find_one({login => 'test'}  => sub { ...
```

Empirically I found that correct way is:

```perl
has dbh => sub {
  my $self = shift;
  my $mango = Mango->new('mongodb://localhost:27017');
  return $mango;
};
...
 $self->app->dbh->db('mongopa')->collection('users')->find_one({login => 'test'}  => sub { ...
```
I found in irc #mojo channel logs [comment](https://irclog.perlgeek.de/mojo/2013-08-29/text) from @kraih that that we need to avoid using db() in helpers cause of weakened reference. Okay, but I haven't found any examples how to avoid repeating database declaration in queries at code.

E.g. I want to set default database to 'test'. As I understood from docs I can do this two ways. First one to add database name to uri of connection (uses [from_string](https://metacpan.org/pod/Mango#from_string) method - ? ):

```perl
has dbh => sub {
  my $self = shift;
  my $mango = Mango->new('mongodb://localhost:27017/test');
  return $mango;
};
```
or with [default_db](https://metacpan.org/pod/Mango#default_db) method:

```perl
has dbh => sub {
  my $self = shift;
  my $mango = Mango->new('mongodb://localhost:27017/');
  $mango->default_db('test');
  return $mango;
};
```

But ```$self->app->dbh->collection('users')->find_one({login => 'user1'}...``` doesn't work.  Error ```Can't locate object method "collection" via package "Mango"``` in both cases.

So now I got stuck with using Mango in my projects. Maybe I did something wrong cause some documentation is missing. Btw, I'm [not the first ](https://irclog.perlgeek.de/mojo/2013-08-29/text) who wasted time before figure out it. Please add some documentation.

**Comment by alexbyk** [comment]
+1, this repository needs some examples.

I made one file application here to help you(and others). It covers your questions. If someone get stuck, "copy and modify".

Check it out: https://gist.github.com/alexbyk/908dd9d2439e45fb0027023f2a6ab4ac

**Comment by oliwer** [comment]
Agreed. I will look into this.

**Comment by paulserikov** [comment]
@alexbyk, thank you for example but it didn't help me.

Firstly I don't understand why do you mango and collection helpers return nothing.

Secondly I don't understand why did you defined collection helper, Mango::Database already [has](https://metacpan.org/pod/Mango::Database#collection) this method.

And finally why do you need $c variable as input parameter in mango helper?

**Comment by alexbyk** [comment]
@paulserikov 
1) in perl last expression is always returned. So i just omitted a `return` statement. Both helpers return objects.
2) I did it because `$self->collection("users")` is shorter than `$c->mango->db->collection('users')`, see comment in example above that line.
3) I don't need `$c`, you're right. I wrote it just for consistence

**Comment by paulserikov** [comment]
@alexbyk thank you for detailed explanation ! Now I succeed with intergration of your code into my project.

I'm just using perl v 5.18.2 so it's not possible to use experimental features. So I [rewrote](https://gist.github.com/paulserikov/d6b67dce754fa4c1f3b88942bab68b88) your example app :)
