### ISSUE TITLE
Any example how to use $mango->query ?

### ISSUE THREAD

**Issue by pavelsr** [oliwer/mango#19]
Is it possible to execute [db.loadServerScripts()](https://docs.mongodb.com/manual/reference/method/db.loadServerScripts/) via this method? And what about usage of Javascript functions?

Let me give you a particular example. I created a Javascript function at system.js collection which implements [auto-incrementing](https://docs.mongodb.com/v3.0/tutorial/create-an-auto-incrementing-field/).

Script for [Mongo shell](https://docs.mongodb.com/master/tutorial/write-scripts-for-the-mongo-shell/) looks like:

```javascript
db.dropDatabase();
db.counters.insert({_id: "userid", seq: 0 });
db.system.js.save({
	_id: "getNextSequence",
	value: function (name) {
	    var ret = db.counters.findAndModify({
	        query: { _id: name },
	        update: { $inc: { seq: 1 } },
	        new: true
	    });
	   return ret.seq;
	}
});
db.loadServerScripts();
db.users.insert({"login":"demo","user_id":getNextSequence("userid"),"password":"demo"});
```
(run it via `mongo localhost:27017/mongopa init_db.js` command)

But how to execute last two strings via Mango driver? Is it possible at all?

I tried to execute:

```perl
use Mango;
use Data::Dumper;
my $mango = Mango->new('mongodb://localhost:27017/mongopa');
my $reply  = $mango->query({}, {}, {}, {}, loadServerScripts(), {});
warn Dumper $reply;
my $oid = $mango->collection('users')->insert({'user_id' => 'getNextSequence("userid")', 'login' => 'demo2', 'password' => 'demo2' });
warn Dumper $oid;
```
but I got an error `Undefined subroutine &main::loadServerScripts called ...`

What am I doing wrong and could you please provide any example how to use [$mango->query](https://metacpan.org/pod/Mango#query) ?

**Comment by oliwer** [comment]
Hi. I'm afraid calling saved script is impossible for now. Even in the official MongoDB driver, we are asked to [rewrite the scripts in perl](https://metacpan.org/pod/distribution/MongoDB/lib/MongoDB/Examples.pod#DATABASE-COMMANDS). And `loadServerScripts` only works in the MongoDB shell.

Maybe @xdg could tell us more?

**Comment by xdg** [comment]
The mongo shell is written in JavaScript, so I think that database command just pulls down code and evals it it the shell. The Perl equivalent is to save Perl code (as text), in a collection, pull it down and then run it with `eval()`. Personally, I think that's not a robust, testable design, so I'd recommend just writing a Perl module with whatever reusable functions you want.

**Comment by oliwer** [comment]
Thanks for clearing that up.
