### ISSUE TITLE
Can't work with non-standart $oid

### ISSUE THREAD

**Issue by pavelsr** [oliwer/mango#20]
I have such collection:

```javascript
> db.counters.find()
{ "_id" : "userid", "seq" : 1 }
```
when I do

```perl
$mango->db->collection('counters')->update('userid', {'seq' => '2'} );
```

I got an error:

```
wrong type for 'q' field, expected object, found q: "userid"
```

I looked at [Mango::Collection code](https://metacpan.org/source/ODC/Mango-1.28/lib/Mango/Collection.pm#L211) and found this string:

```perl
q => ref $query eq 'Mango::BSON::ObjectID' ? {_id => $query} : $query,
```

maybe we should correct it to:

```perl
q => ref $query eq 'HASH' ?  $query : {_id => $query},
```

and same way other methods. Already made a fork and [pull request.](https://github.com/oliwer/mango/pull/21)

@oliwer , please let me know what do you think about it.

**Comment by alexbyk** [comment]
When the first argument to the invocation of ```find_one``` is an instance of ```Mango::BSON::ObjectID```, the query will be considered as a shortcut for ```{_id => $bson_oid}```.

So: ```->find_one($oid)``` eq ```->find_one({_id => $oid})```,
 and ```->update($oid, {foo => 22})``` eq ```->update({_id => $oid}, {foo => 22})```

The current code is ok, and your commit breaks this feature.

Your code snippet throws an error because it's not an```ObjectID``` (as it should be in most cases). If you're sure that using strings instead of OIDs is a good idea, your should rewrite your code this way : ```->update({_id => 'userid'}, {seq => 2})```. But using ObjectIDs for ```_id``` fields would be a better choice.

**Comment by alexbyk** [comment]
Updated answer: this may break an existing code where a 'query' argument is a blessed object. Also in my opinion using "strings" instead of ObjectIDs in _id fields is a bad practice, and this commit encourages it

**Comment by oliwer** [comment]
I'm going to vote :-1:  here. The choice of only accepting OIDs as the first argument was well thought by the original author. It helps a lot catching cases where you forgot to cast a string (that you got from a json for instance) as a proper ObjectID. And as alexbyk said, there are many cases where people pass blessed objects.

Sorry to reject your PR (which lacks documentation changes btw) but it's for your own good.
