### ISSUE TITLE
MongoDB adding BSON Decimal128 type

### ISSUE THREAD

**Issue by xdg** [oliwer/mango#22]
This is a heads up that MongoDB 3.4 will add a new BSON type: Decimal128.

A note for 3rd party driver authors is copied below:

```
MongoDB 3.4 (or more specifically, current development release, MongoDB 3.3.8) introduces
a new BSON data type, called Decimal128. See SERVER-1393.

We just published the final drivers spec for handling this new type (see also DRIVERS-288):
https://github.com/mongodb/specifications/blob/master/source/bson-decimal128/decimal128.rst
```

I've added support for this in the development release of the pure-Perl BSON distribution [v0.999.0](https://metacpan.org/release/MONGODB/BSON-v0.999.0-TRIAL) or later.  The MongoDB driver v1.6.0 (under development) will depend on that distribution's BSON::Decimal128 module for Decimal128 support.

In the long run, I'd like to see the Mango BSON classes become empty subclasses of the pure-Perl BSON classes and for the Mango BSON encoder to delegate to the pure-Perl BSON encoder, so that you can benefit from ongoing support and development.  That's probably a separate issue to discuss.  :-)

**Comment by oliwer** [comment]
Thanks for the update. Mango will support Decimal128 when it has switched to the official BSON module.
