### ISSUE TITLE
Mango Aggregate Max 100 Records

### ISSUE THREAD

**Issue by dexteruk** [oliwer/mango#24]
Hi, im trying to return all records in an Aggregate that im using for a live search.  But it only returns 100 records at a time.  I have tried increasing the {'$limit' => 1000} but it still returns 100 records.  I have changed it to 50 and it returned 50 so i know the limit is working.  

I have chatted with people in the IRC #mongodb they tell me there is no limit on the number of records the aggregate should be returning.

Any help would be greatly appreciated.

Thanks

**Comment by oliwer** [comment]
Hello! It's hard to know exactly what you are doing without a code example, but instead of using $limit, you could try setting the cursor size used by MongoDB like this:

    $collection->aggregate($pipeline, { cursor => { batchSize: 500 }});

Tell me if it changes anything. I'll try to do more tests tonight.

**Comment by dexteruk** [comment]
Hi Olivier

I found out that

$collection->aggregate({Your Query})->all

Returned all the data in one go, actually i thought i tried this
before i sent you an message.  But last night I was

trying all sorts of stuff and i tried this one and it worked without
causing me any issues.

Thanks

Dexteruk

**Comment by oliwer** [comment]
You had me worried! Indeed, aggregate() returns a Mango::Cursor object.
