### ISSUE TITLE
TTL and ISODate

### ISSUE THREAD

**Issue by dexteruk** [oliwer/mango#25]
Problem passing the correct format for the TTL to work with mongodb.

After setting up Expire Date in the mongodb following these instructions 
https://docs.mongodb.com/manual/tutorial/expire-data/

When i create a document using the mongo shell 

db.test.insert({"lastModifiedDate" : new Date(),"test": "test"})

when i look at the data it returns me not only the date in ISODate format but its also wrapped with a function ISODate("")

{ "_id" : ObjectId("58fc7bbc4f3e452029a4f786"), "lastModifiedDate" : ISODate("2017-04-23T10:02:36.563Z"), "test" : "test" }

I have not yet found away to create the same thing passing it from perl, and from perl if i simply send a ISO date, mongodb does not remove it.  But yet using the shell and creating as above it removes it after 30 seconds.

I found some information talking about how use can do this using MongoDB::Code

http://stackoverflow.com/questions/13872884/insert-mongodb-server-date-from-perl-driver

But im using mango on Mojolicious and i seem to be able to find away to achieve the same.

Thanks for your help

Craig

**Comment by dexteruk** [comment]
sorry just found it use lastModifiedDate => bson_time

**Comment by oliwer** [comment]
I may add an example to the documentation later.
