### ISSUE TITLE
SCRAM-SHA-1 auth.?

### ISSUE THREAD

**Issue by alexbyk** [oliwer/mango#3]
Hi. Do you plan to implement new auth. SCRAM-SHA-1 ?

**Comment by dagolden** [comment]
FWIW, it shouldn't be terribly hard to do.  I wrote [Authen::SCRAM](https://metacpan.org/pod/Authen::SCRAM) to do the hard work.  You can see the authentication conversation in the official driver here: https://github.com/mongodb/mongo-perl-driver/blob/master/lib/MongoDB/_Credential.pm#L276-L296

**Comment by alexbyk** [comment]
@dagolden yes, thanks for your work, I've already made a draft release of Mango working somehow with 3.0 using your module here https://github.com/alexbyk/mango (https://travis-ci.org/alexbyk/mango) - I didn't know that someone still maintain this module before kraih wrote me about that in gg.

**Comment by alexbyk** [comment]
So I was going to rewrite Mango.pm but when I found that oliwer maintains it, I decided to ask maybe he already working on it to avoid do the same thing twice

**Comment by alexbyk** [comment]
I made it working here https://github.com/alexbyk/mango - @oliwer could you please connect with me?

**Comment by oliwer** [comment]
Thank you very much @alexbyk for implementing this. I agree we can forget about MONGO-CR support.

I will certainly include this into the next release if you think it is ready for production. I cannot just import all your patches in bulk though as i am implementing mongodb3 support slightly differently than you.

**Comment by alexbyk** [comment]
If you mean "is MongoDB 3.0 ready for production" - I think this release is awesome and I've updated all my project without hesitation. But I need to mention that I think "using old but stable versions of products" is an excuse for lazy developers, that's why I'm using perl 5.20 in my projects with many experimental features: If they change in the next release, I'll just rewrite my code. Not everyone share this opinion.

And @oliwer , please next time be more opensource. If I knew you're already working on this release we can work together and made it faster. You could just create a branch 3.0 to show that something's going on and this fork isn't abandoned

Because I didn't find any changes in this repository, I decided to made it by myself. And if you're talking that you're already working on it (maybe using your private repo), looks like Mango just splitted in 2 different forks.

Also if you're only going to start working on it, you can consider maybe it will be simpler to just switch to my fork and release it, using it as a start point. But if you already started, you can at least look and copypaste some ideas. You can also take a look at the @dagolden 's message above. I can confirm that implementing authenication wasn't difficult with the help of his Authen::SCRAM 

Thank you for your work. Good luck!
