### ISSUE TITLE
Different result after aggregation.

### ISSUE THREAD

**Issue by Spear5030** [oliwer/mango#5]
I have collection 'books': 
{
    "_id" : ObjectId("54901b078b823f2014080700"),
    "title" : "title1",
    "available" : 0,
    "time" : 14318789245,
    "score" : 1,
   "categories" : [ 
        "fiction", 
        "humor"
    ]
},
{
    "_id" : ObjectId("54901b078b823f2014080701"),
    "title" : "title2",
    "available" : 1,
    "time" : 14318789745,
    "score" : 1,
    "score_fiction": 5,
    "categories" : [ 
        "fiction", 
    ]
}
...
{
    "_id" : ObjectId("54901b078b823f2014080751"),
    "title" : "titleN",
    "available" : 1,
    "time" : 14318789545,
    "score" : 4,
    "score_fiction": 2,
}

I will aggregate it with this script:
my $books = $mango->db('test')->collection('books')->aggregate(
    [
    {'$match' => {categories => fiction}},
    {'$project' => {
                 'av' => {'$cmp' => ['$available', 0] },
                 title => 1,
                 scr => {'$ifNull' => ['$score_fiction' , '$score'] },
                 time =>1}
    },
    {'$sort' => {av => -1, scr => -1, time => -1}},
    {'$limit' =>  10}
    ]
);

while (my $book = $books->next) {
print $book->{title} . " [" . $book->{scr} . "]\n";

After 5-7 runs I get two different results: 
1. With sorting by required fields. 
2. Without sorting. (possibly with sorting by time or the "$natural" time of addition).

When I run this aggregation pipeline in mongo's shell - it works with correctly sorting.
db.books.aggregate([{'$match' : {categories : 'fiction'},
{'$project' : {'av' : {'$cmp' : ['$available', 0] },
  title : 1,
  scr : {'$ifNull' : ['$score_fiction' , '$score'] },
  time:1}},
{'$sort' : {av : -1,scr :-1, time : -1}},
{'$limit':  10}]);

Is the problem in the driver or in my head?

**Comment by dagolden** [comment]
`{'$sort' => {av => -1, scr => -1, time => -1}},`

This is likely to be the issue if you're on a recent perl that randomizes hash order.  The sort clause needs to be an ordered document.  See https://metacpan.org/pod/Mango::BSON#bson_doc for how to do that.

`{'$match' => {categories => fiction}},`

Nit: is the lack of quotes around "fiction" actually in your code or is it a typo transcribing to github?

**Comment by Spear5030** [comment]
Oh! Thank you. It works.
The random nature of the result was to bring me to the hashes.
