### ISSUE TITLE
Mango 1.18 is not working with SCRAM-SHA1 authentication mechanism

### ISSUE THREAD

**Issue by uynap** [oliwer/mango#6]
When I use Mango 1.17/1.18 together with MongoDB 3.0(MONGODB-CR), everything's fine. But when I switch the MongoDB mechanism version 3 to 5(MONGODB-CR to SCRAM-SHA1), 1.17 will give me error message like "authentication failed" which is right. Whereas Mango 1.18 will throw "can't located Mango/Auth/SCRAM.pm....." which is misleading. I expected something like "required Authen::SCRAM". 
Actually, installing Authen::SCRAM with Mango 1.18 cannot solve the problem. Still the same error message. 
For issue recreation, make sure the MongoDB 3.0.* is using MONGODB-CR. 
> db.system.version.findOne({"_id" : "authSchema"})
{ "_id" : "authSchema", "currentVersion" : 5 }
>
Connect the DB with Mango 1.18 will give you the error message.

**Comment by ashrafhasson** [comment]
I'm facing the same issue with Mango 1.18, Mango::Auth::SCRAM doesn't seem to be part of the package that's released to MetaCPAN or CPAN but it is there in the git repo!

**Comment by ashrafhasson** [comment]
just to confirm, if you install directly from the archive of this repo, Auth is installed fine:
```bash
cpanm https://github.com/oliwer/mango/archive/v1.18.zip
```

**Comment by alexbyk** [comment]
Hi, guys. Oliwer just forgot to include Mango/Auth/Scram.pm in the final release (or MANIFEST file is missing, that depends on...).

So Mango@CPAN is broken right now, you can only wait when the author fix this issue or use a temporary solution `cpanm https://github.com/oliwer/mango/archive/v1.18.zip`

**Comment by oliwer** [comment]
Yup. Sorry about this -_-

I am far away from my computer these days so i couldnt fix it. I will do a
new release next week.
