### ISSUE TITLE
find_and_modify is changing the ObjectID on the document it modifies

### ISSUE THREAD

**Issue by ashrafhasson** [oliwer/mango#8]
It seems as though the find_and_modify method is altering the ObjectID of the document it's modifying when it shouldn't compared to the native MongoDB shell.

    #!/usr/env perl
    use Mango;
    use Mango::BSON ':bson';

    my $uri = 'mongodb://localhost/test';
    my $mango = Mango->new($uri);
    my $oid = $mango->db->collection('mytable')->insert({field1 => 'original'});

    my $updated_doc = $mango->db->collection('mytable')->find_and_modify({query => $oid, update => {'$set' => {field1 => 'updated'}}, new => bson_true});
    print $updated_doc->{_id} ne $oid ? "oops, OID was modified\n" : "things look okay!\n";

**Comment by ashrafhasson** [comment]
Apologies, please ignore this, the issue is not in the driver rather somewhere else in my code.

**Comment by ashrafhasson** [comment]
After further testing I found that the statement above holds true and that Mango seem to be changing the OID when running find_and_modify.

**Comment by oliwer** [comment]
I think i have found what makes you think that :

    find_and_modify({query => $oid,

This is incorrect. The fact that it works on first execution is pure luck. You must write this instead :

    find_and_modify({query => { _id => $oid },

Contrary to other commands like `find` or `remove`, `find_and_modify` cannot guess that you are querying the ObjectID. You have to be specific.

**Comment by ashrafhasson** [comment]
Oh, thank you for clarifying that, yeah I made an assumption there I guess. Changing the query to `{ _id => $oid }` sets the behaviour as expected.
